# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-02 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operator',
            },
        ),
    ]
