# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-02 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wlibrary',
            name='mcdc_1',
            field=models.CharField(max_length=64, verbose_name='mcdc_1'),
        ),
        migrations.AlterField(
            model_name='wlibrary',
            name='mcdc_2',
            field=models.CharField(max_length=64, verbose_name='mcdc_2'),
        ),
    ]
