# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-02 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180902_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t11', models.CharField(default='', max_length=64, verbose_name='t11')),
                ('operator1', models.CharField(default='', max_length=54)),
                ('t12', models.CharField(default='', max_length=64)),
                ('exp', models.CharField(max_length=500, verbose_name='Description')),
                ('t21', models.CharField(default='', max_length=64)),
                ('operator2', models.CharField(default='', max_length=54)),
                ('t22', models.CharField(default='', max_length=64)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Nexus', verbose_name='R_name')),
            ],
            options={
                'verbose_name': 't11',
                'verbose_name_plural': 't11',
            },
        ),
    ]
