# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-02 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180902_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation2',
            options={'verbose_name': 'relationship_operator', 'verbose_name_plural': 'relationship_operator'},
        ),
    ]
