# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-03 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_relation2_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation2',
            name='ref',
            field=models.CharField(default='', max_length=500, verbose_name='Reference'),
        ),
    ]
